# Упражнения "Работа с тензорами в PyTorch"

Задание 1. Импортируйте PyTorch и посмотрите версию.

In [2]:
import torch

In [3]:
# ваш код здесь
print(torch.__version__)

2.9.0+cpu


Задание 2. Создайте одномерный тензор чисел от 0 до 9.

Желаемый результат:

> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# ваш код здесь
tensor = torch.arange(0,10)
print(tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


Задание 3. Для тензора, созданного в задании 2, выведите


*   тип элементов
*   размер
*   количество размерностей



In [5]:
# ваш код здесь
print(
    f"Вектор:\n{tensor}",
    f"Размеры вектора                --> {tensor.shape}",
    f"Количество размерностей        --> {tensor.dim()}",
    f"Какого типа элементы вектора   --> {tensor.dtype}",
    sep="\n\n",
)

Вектор:
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Размеры вектора                --> torch.Size([10])

Количество размерностей        --> 1

Какого типа элементы вектора   --> torch.int64


Задание 4. Разделите тензор из задания 2 на две половины (левую - начало тензора и правую - его конец). Выведите обе эти половины.

In [6]:
# ваш код здеcь
c=tensor[:5]
p=tensor[5:]
print(c,p)

tensor([0, 1, 2, 3, 4]) tensor([5, 6, 7, 8, 9])


Задание 5. Создайте вещественный массив размером $3 \times 4$, в котором все элементы равны 1.

In [7]:
# ваш код здесь
torch.ones(3, 4, dtype=torch.double)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)

Задание 6. Создайте логический массив размером $5 \times 2$, в котором все элементы равны True.

In [8]:
# ваш код здесь
torch.ones(5, 2, dtype=torch.bool)


tensor([[True, True],
        [True, True],
        [True, True],
        [True, True],
        [True, True]])

Задание 7. Создайте одномерный тензор с последовательностью вещественных чисел от 1 до 15 включительно, в котором каждый следующий элемент отличается от предыдущего на 0.5

In [9]:
# ваш код здесь
torch.arange(1, 15.1, 0.5)

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000,
        13.0000, 13.5000, 14.0000, 14.5000, 15.0000])

Задание 8. Создайте одномерный тензор, в котором ровно 20 значений. Первой значение 1, последнее значение 10, а расстояние между каждыми двумя соседними элементами одинаково.

In [10]:
# ваш код здесь
torch.linspace(1, 10, 20)

tensor([ 1.0000,  1.4737,  1.9474,  2.4211,  2.8947,  3.3684,  3.8421,  4.3158,
         4.7895,  5.2632,  5.7368,  6.2105,  6.6842,  7.1579,  7.6316,  8.1053,
         8.5789,  9.0526,  9.5263, 10.0000])

Задание 9. Создайте двумерный тензор случайных вещественных значений размером $4 \times 3$ из равномерного распределения на полуинтервале [0, 1).

In [ ]:
# ваш код здесь
torch.rand(4, 3, dtype=torch.float32)

tensor([[0.9917, 0.7843, 0.1224],
        [0.7532, 0.5148, 0.9842],
        [0.8626, 0.6861, 0.5429],
        [0.4371, 0.1240, 0.3956]])

Задание 10. Создайте одномерный тензор 100 случайных "школьных оценок", а именно целых значений из промежутка от 3 до 5 включительно.

In [11]:
# ваш код здесь
t=torch.randint(3, 6,(100,))
t

tensor([3, 5, 5, 4, 4, 5, 4, 5, 3, 5, 4, 3, 5, 4, 4, 3, 4, 4, 3, 5, 3, 4, 4, 3,
        3, 5, 5, 4, 4, 5, 4, 4, 5, 5, 3, 3, 5, 3, 3, 4, 3, 3, 5, 4, 5, 5, 3, 3,
        3, 5, 3, 5, 3, 4, 3, 4, 3, 3, 4, 4, 3, 4, 3, 4, 5, 3, 5, 4, 5, 3, 3, 5,
        3, 4, 3, 3, 4, 5, 4, 4, 4, 4, 4, 3, 4, 5, 3, 5, 3, 4, 3, 3, 4, 3, 4, 4,
        5, 5, 3, 4])

Задание 11. Для тензора "школьных оценок", созданного в задании 10, посчитайте и выведите минимум, максимум и среднее арифметическое.

In [12]:
# ваш код здесь
print(
    f"Максимальное значение:\n{t.max()}",
    f"Минимальное значение:\n{t.min()}",
    f"Среднее арифметическое элементов:\n{t.float().mean()}",
    sep="\n\n",
)

Максимальное значение:
5

Минимальное значение:
3

Среднее арифметическое элементов:
3.9000000953674316


Задание 12. Создайте булеву маску для массива "школьных оценок" из задания 10, в которой True будет стоять для первых 5 оценок и для последних 5 оценок, а остальные значения будут False.

In [13]:
# ваш код здесь
m = torch.zeros_like(t, dtype=torch.bool)
m[:5] = True
m[-5:] = True
print(m)

tensor([ True,  True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False,  True,  True,  True,  True,  True])


Задание 13. Отфильтруйте тензор "школьных оценок", созданный в задании 10, с помощью маски, созданной в задании 12, оставив тем самым только первые и последние пять оценок.

In [14]:
# ваш код здесь

f= t[torch.cat([
    torch.ones(5, dtype=torch.bool),
    torch.zeros(90, dtype=torch.bool),
    torch.ones(5, dtype=torch.bool)
])]
print(f)


tensor([3, 5, 5, 4, 4, 4, 5, 5, 3, 4])


Задание 14. Создайте маску для тензора "школьных оценок", в которой для каждой "пятерки" будет стоять True, а для остальных значений будет стоять False.

In [ ]:
# ваш код здесь
m = t == 5
print(m)

tensor([False,  True, False,  True,  True,  True,  True,  True, False, False,
        False,  True,  True, False, False,  True, False, False, False, False,
        False, False, False, False,  True, False, False, False, False, False,
         True, False,  True, False, False,  True, False, False,  True,  True,
        False, False,  True,  True,  True, False,  True, False,  True, False,
        False, False, False, False, False, False,  True,  True, False,  True,
        False,  True, False,  True,  True, False, False, False, False, False,
         True,  True,  True, False,  True, False, False, False,  True,  True,
        False, False,  True, False,  True, False, False, False,  True, False,
         True, False, False, False, False, False, False,  True,  True, False])


Задание 15. Извлеките все "пятерки" из тензора "школьных отенок", созданного в задании 10, и занесите их в новый тензор.


In [15]:
# ваш код здесь
tensor = t[t == 5]
print(tensor)

tensor([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5])


Задание 16. Преобразуйте тензор "школьных оценок" в двумерный тензор с 5 строками размером $5 \times 20$.


In [16]:
# ваш код здесь
t2 = t.view(5, 20)
print(t2)

tensor([[3, 5, 5, 4, 4, 5, 4, 5, 3, 5, 4, 3, 5, 4, 4, 3, 4, 4, 3, 5],
        [3, 4, 4, 3, 3, 5, 5, 4, 4, 5, 4, 4, 5, 5, 3, 3, 5, 3, 3, 4],
        [3, 3, 5, 4, 5, 5, 3, 3, 3, 5, 3, 5, 3, 4, 3, 4, 3, 3, 4, 4],
        [3, 4, 3, 4, 5, 3, 5, 4, 5, 3, 3, 5, 3, 4, 3, 3, 4, 5, 4, 4],
        [4, 4, 4, 3, 4, 5, 3, 5, 3, 4, 3, 3, 4, 3, 4, 4, 5, 5, 3, 4]])


Задание 17. Выполните стыковку тензоров a и b по вертикали.

Вход:

> a = torch.arange(2, 10, 2).reshape(2, -1)

> b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $4 \times 5$.


In [32]:
# ваш код здесь
a = torch.arange(2, 22, 2).reshape(2, -1)
b = torch.arange(1, 21, 2).reshape(2, -1)
t_17 = torch.cat([a, b], dim=0)
print(t_17)

tensor([[ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]])


Задание 18. Выполните стыковку тензоров a и b по горизонтали.

Вход:

a = torch.arange(2, 10, 2).reshape(2, -1)

b = torch.repeat(1, 10).reshape(2, -1)

Желаемый результат: новый тензор размером $2 \times 10$.

In [33]:
# ваш код здесь
# Минимальное решение
a = torch.arange(2, 22, 2).reshape(2, -1)
b = torch.arange(1, 21, 2).reshape(2, -1)
t_18 = torch.cat([a, b], dim=1)
print(t_18)


tensor([[ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9],
        [12, 14, 16, 18, 20, 11, 13, 15, 17, 19]])


Задание 19. Получите все элементы от 5 до 10 в тензоре a.

Вход:

> a = torch.tensor([2, 6, 1, 9, 10, 3, 27])

Желаемый результат:

> tensor([6, 9, 10])

In [34]:
# ваш код здесь
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
result = a[(a >= 5) & (a <= 10)]
print(result)

tensor([ 6,  9, 10])


Задание 20. Вывести первую строку матрицы из задания 18.

In [35]:
# ваш код здесь
print(t_18[0,:])

tensor([ 2,  4,  6,  8, 10,  1,  3,  5,  7,  9])


Задание 21. Вывести последний столбец матрицы из задания 17.

In [36]:
# ваш код здесь
print(t_17[:, -1])

tensor([10, 20,  9, 19])


Задание 22. Вывести центральную часть матрицы из задания 17 (размерностью $2 \times 3$).

In [37]:
# ваш код здесь
с = t_17[1:3, 1:4]
print(с)

tensor([[14, 16, 18],
        [ 3,  5,  7]])


Задание 23. Вставить в двумерный терзор из задания 17 строку из минимального элемента перед первой строкой.

In [38]:
# ваш код здесь
min_element = t_17.min().item()
min_row = torch.full((1, 5), min_element)
t = torch.cat([min_row, t_17], dim=0)
print(t)

tensor([[ 1,  1,  1,  1,  1],
        [ 2,  4,  6,  8, 10],
        [12, 14, 16, 18, 20],
        [ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]])


Задание 24.	В тензоре, полученном при выполнении задания 23, каждый элемент заменить его корнем квадратным.

In [39]:
# ваш код здесь
t_24 = torch.sqrt(t)
print(t_24)

tensor([[1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
        [1.4142, 2.0000, 2.4495, 2.8284, 3.1623],
        [3.4641, 3.7417, 4.0000, 4.2426, 4.4721],
        [1.0000, 1.7321, 2.2361, 2.6458, 3.0000],
        [3.3166, 3.6056, 3.8730, 4.1231, 4.3589]])


Задание 25.	Заменить в тензоре из задания 18 все значения, кратные 3 или 2 на число 1, а остальные – оставить без изменений.

In [40]:
# ваш код здесь
mask = (t_18 % 2 == 0) | (t_18 % 3 == 0)
result = t_18.clone()
result[mask] = 1
print(result)

tensor([[ 1,  1,  1,  1,  1,  1,  1,  5,  7,  1],
        [ 1,  1,  1,  1,  1, 11, 13,  1, 17, 19]])
